import "./globals.css"

import type { Metadata } from "next"
import { Noto_Sans_Hebrew } from "next/font/google"
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from "next-intl/server"

import { Toaster } from "@/components/ui/sonner"
import { getAppData } from "@/config/app/app.config"
import { AppProvider } from "@/context/app-context"
import { cn } from "@/lib/utils"

const notoSansHebrew = Noto_Sans_Hebrew({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["hebrew"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const messages = await getMessages()
  const appData = getAppData()

  return (
    <html dir="rtl">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          notoSansHebrew.className,
        )}
      >
        <AppProvider value={appData}>
          <NextIntlClientProvider messages={messages}>
            {children}
            <Toaster />
          </NextIntlClientProvider>
        </AppProvider>
      </body>
    </html>
  )
}
