import "./globals.css"

import type { Metadata } from "next"
import { Noto_Sans_Hebrew } from "next/font/google"

import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils"

const notoSansHebrew = Noto_Sans_Hebrew({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["hebrew"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html dir="rtl">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          notoSansHebrew.className,
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  )
}
