name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Quality Checks (Lint, Typecheck)
        run: pnpm turbo lint type:check

      - name: Generate Prisma Client
        run: pnpm prisma generate --schema=apps/backend/prisma/schema.prisma
        working-directory: apps/backend

      - name: Build
        run: |
          export DATABASE_URL="mongodb://localhost:27017/core-ecommerce"
          export ADMIN_PASSWORD="mock"
          export CLOUDINARY_CLOUD_NAME="mock"
          export CLOUDINARY_API_KEY="mock"
          export CLOUDINARY_API_SECRET="mock"
          export AUTH_JWT_SECRET="mock"
          export NEXT_PUBLIC_APP_NAME="mock"
          export NEXT_PUBLIC_APP_URL="mock"
          export NEXT_PUBLIC_SERVER_URL="mock"
          export NEXT_PUBLIC_APP_TYPE="FOOD"

          pnpm turbo build
