name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })' || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      DATABASE_URL: "mongodb://localhost:27017/core-ecommerce"
      ADMIN_PASSWORD: "mock"
      CLOUDINARY_CLOUD_NAME: "mock"
      CLOUDINARY_API_KEY: "mock"
      CLOUDINARY_API_SECRET: "mock"
      AUTH_JWT_SECRET: "mock"
      NEXT_PUBLIC_APP_NAME: "mock"
      NEXT_PUBLIC_APP_URL: "mock"
      NEXT_PUBLIC_SERVER_URL: "mock"
      NEXT_PUBLIC_APP_TYPE: "FOOD"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Quality Checks (Lint, Typecheck)
        run: pnpm turbo lint type:check

      - name: Generate Prisma Client
        run: pnpm prisma generate --schema=prisma/schema.prisma
        working-directory: apps/backend

      - name: Build
        run: pnpm turbo build --cache-dir=.turbo
